import warnings
from typing import Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor
from torch.nn.init import constant_, xavier_normal_, xavier_uniform_

from .arm import AttentionRefinementModule


class MultiheadAttention(nn.Module):
    bias_k: Optional[torch.Tensor]
    bias_v: Optional[torch.Tensor]

    def __init__(
        self,
        embed_dim,
        num_heads,
        dropout=0.0,
        bias=True,
        add_bias_kv=False,
        add_zero_attn=False,
        kdim=None,
        vdim=None,
    ):
        super(MultiheadAttention, self).__init__()
        self.embed_dim = embed_dim
        self.kdim = kdim if kdim is not None else embed_dim
        self.vdim = vdim if vdim is not None else embed_dim
        self._qkv_same_embed_dim = self.kdim == embed_dim and self.vdim == embed_dim

        self.num_heads = num_heads
        self.dropout = dropout
        self.head_dim = embed_dim // num_heads
        assert (
            self.head_dim * num_heads == self.embed_dim
        ), "embed_dim must be divisible by num_heads"

        if self._qkv_same_embed_dim is False:
            self.q_proj_weight = nn.Parameter(torch.Tensor(embed_dim, embed_dim))
            self.k_proj_weight = nn.Parameter(torch.Tensor(embed_dim, self.kdim))
            self.v_proj_weight = nn.Parameter(torch.Tensor(embed_dim, self.vdim))
            self.register_parameter("in_proj_weight", None)
        else:
            self.in_proj_weight = nn.Parameter(torch.empty(3 * embed_dim, embed_dim))
            self.register_parameter("q_proj_weight", None)
            self.register_parameter("k_proj_weight", None)
            self.register_parameter("v_proj_weight", None)

        if bias:
            self.in_proj_bias = nn.Parameter(torch.empty(3 * embed_dim))
        else:
            self.register_parameter("in_proj_bias", None)
        self.out_proj = nn.Linear(embed_dim, embed_dim)

        if add_bias_kv:
            self.bias_k = nn.Parameter(torch.empty(1, 1, embed_dim))
            self.bias_v = nn.Parameter(torch.empty(1, 1, embed_dim))
        else:
            self.bias_k = self.bias_v = None

        self.add_zero_attn = add_zero_attn

        self._reset_parameters()

    def _reset_parameters(self):
        if self._qkv_same_embed_dim:
            xavier_uniform_(self.in_proj_weight)
        else:
            xavier_uniform_(self.q_proj_weight)
            xavier_uniform_(self.k_proj_weight)
            xavier_uniform_(self.v_proj_weight)

        if self.in_proj_bias is not None:
            constant_(self.in_proj_bias, 0.0)
            constant_(self.out_proj.bias, 0.0)
        if self.bias_k is not None:
            xavier_normal_(self.bias_k)
        if self.bias_v is not None:
            xavier_normal_(self.bias_v)

    def __setstate__(self, state):
        # Support loading old MultiheadAttention checkpoints generated by v1.1.0
        if "_qkv_same_embed_dim" not in state:
            state["_qkv_same_embed_dim"] = True

        super(MultiheadAttention, self).__setstate__(state)

    def forward(
        self,
        query: Tensor,
        key: Tensor,
        value: Tensor,
        arm: Optional[AttentionRefinementModule] = None,
        key_padding_mask: Optional[Tensor] = None,
        need_weights: bool = True,
        attn_mask: Optional[Tensor] = None,
    ) -> Tuple[Tensor, Optional[Tensor]]:
        if not self._qkv_same_embed_dim:
            return multi_head_attention_forward(
                query,
                key,
                value,
                arm,
                self.embed_dim,
                self.num_heads,
                self.in_proj_weight,
                self.in_proj_bias,
                self.bias_k,
                self.bias_v,
                self.add_zero_attn,
                self.dropout,
                self.out_proj.weight,
                self.out_proj.bias,
                training=self.training,
                key_padding_mask=key_padding_mask,
                need_weights=need_weights,
                attn_mask=attn_mask,
                use_separate_proj_weight=True,
                q_proj_weight=self.q_proj_weight,
                k_proj_weight=self.k_proj_weight,
                v_proj_weight=self.v_proj_weight,
            )
        else:
            return multi_head_attention_forward(
                query,
                key,
                value,
                arm,
                self.embed_dim,
                self.num_heads,
                self.in_proj_weight,
                self.in_proj_bias,
                self.bias_k,
                self.bias_v,
                self.add_zero_attn,
                self.dropout,
                self.out_proj.weight,
                self.out_proj.bias,
                training=self.training,
                key_padding_mask=key_padding_mask,
                need_weights=need_weights,
                attn_mask=attn_mask,
            )

    def project_kv(self, key: Tensor, value: Tensor) -> Tuple[Tensor, Tensor]:
        """Project key and value for caching. Used only for cross-attention.
        Returns k, v of shape [B * num_heads, src_len, head_dim].
        """
        assert self.bias_k is None and self.bias_v is None
        src_len, bsz, _ = key.size()
        if not self._qkv_same_embed_dim:
            k = F.linear(key, torch.jit._unwrap_optional(self.k_proj_weight), self.in_proj_bias[self.embed_dim : (self.embed_dim * 2)] if self.in_proj_bias is not None else None)
            v = F.linear(value, torch.jit._unwrap_optional(self.v_proj_weight), self.in_proj_bias[(self.embed_dim * 2) :] if self.in_proj_bias is not None else None)
        else:
            if self.in_proj_bias is not None:
                _b_k = self.in_proj_bias[self.embed_dim : self.embed_dim * 2]
                _b_v = self.in_proj_bias[self.embed_dim * 2 :]
            else:
                _b_k = _b_v = None
            _w_k = self.in_proj_weight[self.embed_dim : self.embed_dim * 2, :]
            _w_v = self.in_proj_weight[self.embed_dim * 2 :, :]
            k = F.linear(key, _w_k, _b_k)
            v = F.linear(value, _w_v, _b_v)
            
        k = k.contiguous().view(-1, bsz * self.num_heads, self.head_dim).transpose(0, 1)
        v = v.contiguous().view(-1, bsz * self.num_heads, self.head_dim).transpose(0, 1)
        return k, v

    def forward_step(
        self,
        query: Tensor,
        cached_k: Optional[Tensor] = None,
        cached_v: Optional[Tensor] = None,
        beam_origin: Optional[Tensor] = None,
        arm_fn=None,
        key_padding_mask: Optional[Tensor] = None,
    ) -> Tuple[Tensor, Tensor, Tensor, Tensor]:
        """Single-step forward for inference with KV cache.
        query: [1, B_beam, D]
        cached_k, cached_v:
            - For self-attention: [B_beam * num_heads, T_cached, head_dim]
            - For cross-attention: [B * num_heads, src_len, head_dim]
        beam_origin: [B_beam] (only used for cross-attention)
        
        Returns:
            attn_output: [1, B_beam, D]
            new_cached_k, new_cached_v
            attention: [B_beam * num_heads, 1, src_len]
        """
        tgt_len, bsz, embed_dim = query.size()
        assert tgt_len == 1
        scaling = float(self.head_dim) ** -0.5

        # 1. Project Query
        if not self._qkv_same_embed_dim:
            q = F.linear(query, torch.jit._unwrap_optional(self.q_proj_weight), self.in_proj_bias[0:self.embed_dim] if self.in_proj_bias is not None else None)
        else:
            _w_q = self.in_proj_weight[0:self.embed_dim, :]
            _b_q = self.in_proj_bias[0:self.embed_dim] if self.in_proj_bias is not None else None
            q = F.linear(query, _w_q, _b_q)
            
        q = q * scaling
        q = q.contiguous().view(1, bsz * self.num_heads, self.head_dim).transpose(0, 1) # [B_beam * num_heads, 1, head_dim]

        is_cross_attention = beam_origin is not None

        if not is_cross_attention:
            # SELF-ATTENTION
            # Project current K/V
            if not self._qkv_same_embed_dim:
                k_curr = F.linear(query, torch.jit._unwrap_optional(self.k_proj_weight), self.in_proj_bias[self.embed_dim : (self.embed_dim * 2)] if self.in_proj_bias is not None else None)
                v_curr = F.linear(query, torch.jit._unwrap_optional(self.v_proj_weight), self.in_proj_bias[(self.embed_dim * 2) :] if self.in_proj_bias is not None else None)
            else:
                _w_k = self.in_proj_weight[self.embed_dim : self.embed_dim * 2, :]
                _w_v = self.in_proj_weight[self.embed_dim * 2 :, :]
                _b_k = self.in_proj_bias[self.embed_dim : self.embed_dim * 2] if self.in_proj_bias is not None else None
                _b_v = self.in_proj_bias[self.embed_dim * 2 :] if self.in_proj_bias is not None else None
                k_curr = F.linear(query, _w_k, _b_k)
                v_curr = F.linear(query, _w_v, _b_v)
                
            k_curr = k_curr.contiguous().view(-1, bsz * self.num_heads, self.head_dim).transpose(0, 1)
            v_curr = v_curr.contiguous().view(-1, bsz * self.num_heads, self.head_dim).transpose(0, 1)
            
            # Concat with cache
            if cached_k is not None:
                new_k = torch.cat([cached_k, k_curr], dim=1)
                new_v = torch.cat([cached_v, v_curr], dim=1)
            else:
                new_k, new_v = k_curr, v_curr
                
            # Dots
            attn_output_weights = torch.bmm(q, new_k.transpose(1, 2))
            attention = F.softmax(attn_output_weights, dim=-1)
            attn_output = torch.bmm(attention, new_v)
            
        else:
            # CROSS-ATTENTION
            assert cached_k is not None and cached_v is not None
            B = cached_k.size(0) // self.num_heads
            B_beam = bsz
            src_len = cached_k.size(1)
            
            new_k, new_v = cached_k, cached_v # Unchanged
            
            q_reshaped = q.view(B_beam, self.num_heads, 1, self.head_dim)
            k_reshaped = cached_k.view(B, self.num_heads, src_len, self.head_dim)
            v_reshaped = cached_v.view(B, self.num_heads, src_len, self.head_dim)
            
            attn_output_blocked = torch.empty((B_beam, self.num_heads, 1, self.head_dim), device=q.device, dtype=q.dtype)
            attention_blocked = torch.empty((B_beam, self.num_heads, 1, src_len), device=q.device, dtype=q.dtype)
            
            for s in range(B):
                rows_s = (beam_origin == s).nonzero(as_tuple=True)[0]
                if rows_s.numel() == 0:
                    continue
                    
                q_s = q_reshaped[rows_s] # [count_s, num_heads, 1, head_dim]
                k_s = k_reshaped[s:s+1]  # [1, num_heads, src_len, head_dim]
                v_s = v_reshaped[s:s+1]  # [1, num_heads, src_len, head_dim]
                
                dots_s = torch.matmul(q_s, k_s.transpose(-1, -2)) # [count_s, num_heads, 1, src_len]
                
                if key_padding_mask is not None:
                    # key_padding_mask is [B, src_len]
                    mask_s = key_padding_mask[s:s+1].view(1, 1, 1, src_len).bool()
                    dots_s = dots_s.masked_fill(mask_s, float("-inf"))
                    
                attn_s = F.softmax(dots_s, dim=-1)
                
                if arm_fn is not None:
                    cov = arm_fn(attn_s, rows_s, s)
                    dots_s = dots_s - cov
                    attn_s = F.softmax(dots_s, dim=-1)
                    
                out_s = torch.matmul(attn_s, v_s)
                
                attn_output_blocked[rows_s] = out_s
                attention_blocked[rows_s] = attn_s
                
            attn_output = attn_output_blocked.view(B_beam * self.num_heads, 1, self.head_dim)
            attention = attention_blocked.view(B_beam * self.num_heads, 1, src_len)

        # Common Output Projection
        attn_output = attn_output.transpose(0, 1).contiguous().view(1, bsz, self.embed_dim)
        attn_output = F.linear(attn_output, self.out_proj.weight, self.out_proj.bias)

        return attn_output, new_k, new_v, attention



def multi_head_attention_forward(
    query: Tensor,
    key: Tensor,
    value: Tensor,
    arm: Optional[AttentionRefinementModule],
    embed_dim_to_check: int,
    num_heads: int,
    in_proj_weight: Tensor,
    in_proj_bias: Tensor,
    bias_k: Optional[Tensor],
    bias_v: Optional[Tensor],
    add_zero_attn: bool,
    dropout_p: float,
    out_proj_weight: Tensor,
    out_proj_bias: Tensor,
    training: bool = True,
    key_padding_mask: Optional[Tensor] = None,
    need_weights: bool = True,
    attn_mask: Optional[Tensor] = None,
    use_separate_proj_weight: bool = False,
    q_proj_weight: Optional[Tensor] = None,
    k_proj_weight: Optional[Tensor] = None,
    v_proj_weight: Optional[Tensor] = None,
    static_k: Optional[Tensor] = None,
    static_v: Optional[Tensor] = None,
) -> Tuple[Tensor, Optional[Tensor]]:
    tgt_len, bsz, embed_dim = query.size()
    assert embed_dim == embed_dim_to_check
    # allow MHA to have different sizes for the feature dimension
    assert key.size(0) == value.size(0) and key.size(1) == value.size(1)

    head_dim = embed_dim // num_heads
    assert head_dim * num_heads == embed_dim, "embed_dim must be divisible by num_heads"
    scaling = float(head_dim) ** -0.5

    if not use_separate_proj_weight:
        if (query is key) and (key is value):
            # self-attention
            q, k, v = F.linear(query, in_proj_weight, in_proj_bias).chunk(3, dim=-1)

        elif key is value:
            # encoder-decoder attention
            # This is inline in_proj function with in_proj_weight and in_proj_bias
            _b = in_proj_bias
            _start = 0
            _end = embed_dim
            _w = in_proj_weight[_start:_end, :]
            if _b is not None:
                _b = _b[_start:_end]
            q = F.linear(query, _w, _b)

            if key is None:
                assert value is None
                k = None
                v = None
            else:

                # This is inline in_proj function with in_proj_weight and in_proj_bias
                _b = in_proj_bias
                _start = embed_dim
                _end = None
                _w = in_proj_weight[_start:, :]
                if _b is not None:
                    _b = _b[_start:]
                k, v = F.linear(key, _w, _b).chunk(2, dim=-1)

        else:
            # This is inline in_proj function with in_proj_weight and in_proj_bias
            _b = in_proj_bias
            _start = 0
            _end = embed_dim
            _w = in_proj_weight[_start:_end, :]
            if _b is not None:
                _b = _b[_start:_end]
            q = F.linear(query, _w, _b)

            # This is inline in_proj function with in_proj_weight and in_proj_bias
            _b = in_proj_bias
            _start = embed_dim
            _end = embed_dim * 2
            _w = in_proj_weight[_start:_end, :]
            if _b is not None:
                _b = _b[_start:_end]
            k = F.linear(key, _w, _b)

            # This is inline in_proj function with in_proj_weight and in_proj_bias
            _b = in_proj_bias
            _start = embed_dim * 2
            _end = None
            _w = in_proj_weight[_start:, :]
            if _b is not None:
                _b = _b[_start:]
            v = F.linear(value, _w, _b)
    else:
        q_proj_weight_non_opt = torch.jit._unwrap_optional(q_proj_weight)
        len1, len2 = q_proj_weight_non_opt.size()
        assert len1 == embed_dim and len2 == query.size(-1)

        k_proj_weight_non_opt = torch.jit._unwrap_optional(k_proj_weight)
        len1, len2 = k_proj_weight_non_opt.size()
        assert len1 == embed_dim and len2 == key.size(-1)

        v_proj_weight_non_opt = torch.jit._unwrap_optional(v_proj_weight)
        len1, len2 = v_proj_weight_non_opt.size()
        assert len1 == embed_dim and len2 == value.size(-1)

        if in_proj_bias is not None:
            q = F.linear(query, q_proj_weight_non_opt, in_proj_bias[0:embed_dim])
            k = F.linear(
                key, k_proj_weight_non_opt, in_proj_bias[embed_dim : (embed_dim * 2)]
            )
            v = F.linear(value, v_proj_weight_non_opt, in_proj_bias[(embed_dim * 2) :])
        else:
            q = F.linear(query, q_proj_weight_non_opt, in_proj_bias)
            k = F.linear(key, k_proj_weight_non_opt, in_proj_bias)
            v = F.linear(value, v_proj_weight_non_opt, in_proj_bias)
    q = q * scaling

    if attn_mask is not None:
        assert (
            attn_mask.dtype == torch.float32
            or attn_mask.dtype == torch.float64
            or attn_mask.dtype == torch.float16
            or attn_mask.dtype == torch.uint8
            or attn_mask.dtype == torch.bool
        ), "Only float, byte, and bool types are supported for attn_mask, not {}".format(
            attn_mask.dtype
        )
        if attn_mask.dtype == torch.uint8:
            warnings.warn(
                "Byte tensor for attn_mask in nn.MultiheadAttention is deprecated. Use bool tensor instead."
            )
            attn_mask = attn_mask.to(torch.bool)

        if attn_mask.dim() == 2:
            attn_mask = attn_mask.unsqueeze(0)
            if list(attn_mask.size()) != [1, query.size(0), key.size(0)]:
                raise RuntimeError("The size of the 2D attn_mask is not correct.")
        elif attn_mask.dim() == 3:
            if list(attn_mask.size()) != [bsz * num_heads, query.size(0), key.size(0)]:
                raise RuntimeError("The size of the 3D attn_mask is not correct.")
        else:
            raise RuntimeError(
                "attn_mask's dimension {} is not supported".format(attn_mask.dim())
            )
        # attn_mask's dim is 3 now.

    # convert ByteTensor key_padding_mask to bool
    if key_padding_mask is not None and key_padding_mask.dtype == torch.uint8:
        warnings.warn(
            "Byte tensor for key_padding_mask in nn.MultiheadAttention is deprecated. Use bool tensor instead."
        )
        key_padding_mask = key_padding_mask.to(torch.bool)

    if bias_k is not None and bias_v is not None:
        if static_k is None and static_v is None:
            k = torch.cat([k, bias_k.repeat(1, bsz, 1)])
            v = torch.cat([v, bias_v.repeat(1, bsz, 1)])
            if attn_mask is not None:
                attn_mask = F.pad(attn_mask, (0, 1))
            if key_padding_mask is not None:
                key_padding_mask = F.pad(key_padding_mask, (0, 1))
        else:
            assert static_k is None, "bias cannot be added to static key."
            assert static_v is None, "bias cannot be added to static value."
    else:
        assert bias_k is None
        assert bias_v is None

    q = q.contiguous().view(tgt_len, bsz * num_heads, head_dim).transpose(0, 1)
    if k is not None:
        k = k.contiguous().view(-1, bsz * num_heads, head_dim).transpose(0, 1)
    if v is not None:
        v = v.contiguous().view(-1, bsz * num_heads, head_dim).transpose(0, 1)

    if static_k is not None:
        assert static_k.size(0) == bsz * num_heads
        assert static_k.size(2) == head_dim
        k = static_k

    if static_v is not None:
        assert static_v.size(0) == bsz * num_heads
        assert static_v.size(2) == head_dim
        v = static_v

    src_len = k.size(1)

    if key_padding_mask is not None:
        assert key_padding_mask.size(0) == bsz
        assert key_padding_mask.size(1) == src_len

    if add_zero_attn:
        src_len += 1
        k = torch.cat(
            [
                k,
                torch.zeros(
                    (k.size(0), 1) + k.size()[2:], dtype=k.dtype, device=k.device
                ),
            ],
            dim=1,
        )
        v = torch.cat(
            [
                v,
                torch.zeros(
                    (v.size(0), 1) + v.size()[2:], dtype=v.dtype, device=v.device
                ),
            ],
            dim=1,
        )
        if attn_mask is not None:
            attn_mask = F.pad(attn_mask, (0, 1))
        if key_padding_mask is not None:
            key_padding_mask = F.pad(key_padding_mask, (0, 1))

    attn_output_weights = torch.bmm(q, k.transpose(1, 2))
    assert list(attn_output_weights.size()) == [bsz * num_heads, tgt_len, src_len]

    def mask_softmax_dropout(dots):
        if attn_mask is not None:
            if attn_mask.dtype == torch.bool:
                dots.masked_fill_(attn_mask, float("-inf"))
            else:
                dots += attn_mask

        if key_padding_mask is not None:
            dots = dots.view(bsz, num_heads, tgt_len, src_len)
            dots = dots.masked_fill(
                key_padding_mask.unsqueeze(1).unsqueeze(2),
                float("-inf"),
            )
            dots = dots.view(bsz * num_heads, tgt_len, src_len)

        attn = F.softmax(dots, dim=-1)
        attn = F.dropout(attn, p=dropout_p, training=training)
        return attn

    attention = mask_softmax_dropout(attn_output_weights)
    if arm is not None:
        attn_output_weights -= arm(attention)
        attention = mask_softmax_dropout(attn_output_weights)

    attn_output = torch.bmm(attention, v)
    assert list(attn_output.size()) == [bsz * num_heads, tgt_len, head_dim]
    attn_output = attn_output.transpose(0, 1).contiguous().view(tgt_len, bsz, embed_dim)
    attn_output = F.linear(attn_output, out_proj_weight, out_proj_bias)

    if need_weights:
        return attn_output, attention
    else:
        return attn_output, None
